# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

name: $(Version)$(Rev:.r)

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreCLI@2
  displayName: 'Publish OSX'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/*.csproj'
    arguments: '--output $(build.artifactstagingdirectory)/osx64 -p:Version=$(Version) --configuration $(buildConfiguration) -f netcoreapp3.1 -r osx-x64' 
    zipAfterPublish: true
- task: DotNetCoreCLI@2
  displayName: 'Publish Win'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/*.csproj'
    arguments: '--output $(build.artifactstagingdirectory)/win64 -p:Version=$(Version) --configuration $(buildConfiguration) -f netcoreapp3.1 -r win-x64' 
    zipAfterPublish: true
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
